springdoc:
  show-actuator: true

logging:
  level:
    root: INFO

spring:
  application:
    name: "library-api"
  rabbitmq:
    host: localhost
    port: 21323
    username: guest
    password: guest
    
    template:
      reply-timeout: 30000
    listener:
      direct:
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
        default-requeue-rejected: true
        auto-startup: true

server:
  port: 9002
